routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function(){
    return view('admin.index');
});

Route::get('/home', 'ProductController@feed');

Route::get('logout', 'UserController@logout');

Route::post('user/authenticate', 'UserController@authenticate');
Route::resource('user', 'UserController');

Route::any('product/filter', 'ProductController@filter');
Route::resource('product', 'ProductController');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //

    protected $table = "products";

    public $id;
    public $title;
    public $description;
    public $categories;
    public $value;
    public $quantity;
    public $weight;
    public $user_id;

    protected $fillable = ["id", "title", "description", "categories", "value", "quantity", "weight", "user_id"];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    //
    protected $table = "users";

    public $name;
    public $telephone;
    public $email;
    public $password;
    public $created_at;
    public $updated_at;

    protected $fillable = ['name', 'telephone', 'email', 'password'];

    //protected $guarded = ['remember_token'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models;


class ProductController extends Controller
{
    //
    public function index()
    {
        $products = Models\Product::where('user_id', session('user')->id)->paginate(3);
        return view('product.index', compact('products', 'products'));
    }

    public function feed()
    {
        $products = Models\Product::paginate(3);
        return view('panel.main', compact('products'));
    }

    public function filter(Request $request)
    {
        $dataForm = $request->all();

        $products = Models\Product::where('user_id', session('user')->id)
                    ->where(function ($query) use ($request){
                            if ($request->has('id'))
                                    $query->where('id', $request['id']);
                            if ($request->has('title'))
                                    $query->where('title', $request['title']);
                            if ($request->has('categories'))
                                    $query->where('categories', $request['categories']);
                            if ($request->has('value'))
                                    $query->where('value', $request['value']);
                    })->paginate(3);

        return view('product.index', compact('products', 'dataForm'));

    }

    public function create()
    {
        return view('product.create');
    }

    public function store(Request $request)
    {
        Models\Product::create($request->all());
        return redirect()->back();
    }

    public function show($id)
    {
        $product = json_decode(Models\Product::findOrFail($id));
        return view('product.show', ['product'=>$product]);
    }

    public function edit($id)
    {
        $product = json_decode(Models\Product::findOrFail($id));
        return view('product.edit', ['product' => $product]);
    }

    public function update(Request $request, $id)
    {
        $product = Models\Product::findOrFail($id);
        $product->update($request->all());
        return redirect()->route('product.index');
    }

    public function destroy($id)
    {
        $product = Models\Product::find($id);
        $product->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models;

class UserController extends Controller
{
    //

    public function index()
    {
       return view("user.authenticate");
    }

    public function authenticate(Request $request)
    {
      $user = Models\User::where('email', $request->input('email'))->where('password', $request->input('password'))->first();
      $user = json_decode($user);
      if (isset($user)){
          session(['user' => $user]);
          return redirect()->action('ProductController@feed');
      }
      return redirect()->back()->withInput();

      //return redirect()->route('user.index');
    }

    public function logout()
    {
        session_unset();
        return redirect()->route('user.index');
    }

    public function create()
    {
      return view("user.create");
    }

    public function store(Request $request)
    {
          Models\User::create($request->all());
          return back();
    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $user = json_decode(Models\User::findOrFail($id));
        return view("user.perfil", ["user" => $user]);
    }

    public function update($id)
    {

    }

    public function delete($id)
    {

    }
}

resources/views/admin/index.blade.php
@extends('template')
@section('title', 'Adminx')

@section('content')
<header>
    <div class="row">
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Loja Viegod</a>
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="#">Sair</a>
                </li>
            </ul>
        </nav>
    </div>
</header>

<section>
    <div class="container-fluid">
        <div class="row" style="height: 100%;">
            <div class="col-2" style="background: #3c4167;">
                <ul class="list-unstyled mt-5">

                    <li class="pt-3"> <a href="" style="color: white"> <i class="fas fa-home pr-3" style="font-size: 30px;"></i> Dashboard </a> </li>
                    <li class="pt-3"> <a href="" style="color: white"> <i class="fas fa-cart-plus pr-3" style="font-size: 30px;"></i> Produtos </a> </li>
                    <li class="pt-3"> <a href="" style="color: white"> <i class="fas fa-layer-group pr-3" style="font-size: 30px;"></i> Categorias </a> </li>
                    <li class="pt-3"> <a href="" style="color: white"> <i class="fas fa-users pr-3" style="font-size: 30px;"></i> Usuários </a> </li>
                </ul>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
</section>

<!--
<div class="container-fluid">
<div class="row mt-4">
<div class="col-sm-4">
<div class="sidebar">
<ul class="list-group mt-1">
<li class="list-group-item"> <a href=""> Dashboard </a> </li>
<li class="list-group-item"> <a href=""> Produtos </a> </li>
<li class="list-group-item"> <a href=""> Categorias </a> </li>
<li class="list-group-item"> <a href=""> Usuários </a> </li>
</ul>
</div>
</div>
</div>
</div>

-->
@endsection

resources/views/navbar.blade.php
<!-- Navigation -->
@extends('template')
@section('title', 'Loja Viegod')
@section('content')
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#">
          <img src="http://placehold.it/150x50?text=Logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                @yield('lis')
            </ul>
        </div>
    </div>
</nav>
<!-- Page Content -->
<div class="container">
    <h1 class="mt-4">@yield('h1')</h1>
    <p>@yield('text')</p>
    @yield('content2')
@endsection('content')

resources/views/panel/main.blade.php
@extends('navbar')
@section('lis')
<li class="nav-item active">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>

<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')
@section('h1', 'Produtos da Loja')
@section('text', 'Estes são todos os produtos disponíveis na Loja Virtual Viegod. Você também poderá comprá-los caso desejar.')
@section('content2')

<div class="row">
    @foreach ($products as $product)
    <div class="col-lg-4 col-sm-6 mb-4">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{json_decode($product)->title}}</a>
                </h4>
                <p class="card-text">
                    {{json_decode($product)->description}}
                </p>
            </div>
        </div>
    </div>
    @endforeach
</div>

<!-- Pagination -->
<div class="container pagination justify-content-center">
    @if (isset($dataForm))
        {!! $products->appends($dataForm)->links("pagination::bootstrap-4") !!}
    @else
        {!! $products->links("pagination::bootstrap-4") !!}
    @endif
</div>

</div>
@endsection('content2')
<!-- /.container -->

resources/views/product/create.blade.php
@extends('navbar')

@section('lis')
<li class="nav-item">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')

@section('h1', 'Cadastrar Produto')
@section('text', 'Insira aqui os dados do produto e ele ficará visível a todos usuário, que poderão optar por comprá-lo.')
@section('content2')

<div class="row">
    <div class="col-md-9 col-lg-8">
        <form action="{{route('product.store')}}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="hidden" name="user_id" value="{{session('user')->id}}">
            <div class="form-label-group">
                <input type="text" id="title" name="title" class="form-control" placeholder="Informe o título do produto" value="{{ old('title') }}" required autofocus>
                <label for="title"></label>
            </div>

            <div class="form-label-group">
                <input type="text" id="description" name="description" class="form-control" placeholder="Descrição" value="{{ old('description') }}" required autofocus>
                <label for="description"></label>
            </div>

            <div class="form-label-group">
                <input type="text" id="categories" name="categories" class="form-control" placeholder="Categoria" value="{{ old('categories') }}" required autofocus>
                <label for="categories"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="value" name="value" class="form-control" placeholder="Preço" value="{{ old('value') }}" required>
                <label for="value"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="quantity" name="quantity" class="form-control" placeholder="Quantidade" value="{{ old('quantity') }}" required>
                <label for="quantity"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="weight" name="weight" class="form-control" placeholder="Peso" value="{{ old('weight') }}" required>
                <label for="weight"></label>
            </div>

            <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Cadastrar Produto</button>
        </form>
    </div>
</div>
@endsection('content2')

resources/views/product/edit.blade.php
@extends('navbar')

@section('lis')
<li class="nav-item">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')

@section('h1', 'Editar Produto')
@section('text', 'Abaixo encontram-se os dados referentes ao produto selecionado. Cuidado ao confirmar suas mudanças, elas serão salvas.')
@section('content2')

<div class="row">
    <div class="col-md-9 col-lg-8">
        <form action="{{ route('product.update', ['id' => $product->id]) }}" method="POST">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="form-label-group">
                <input type="text" id="title" name="title" class="form-control" placeholder="Informe o título do produto" value="{{ $product->title  }}" required autofocus>
                <label for="title"></label>
            </div>

            <div class="form-label-group">
                <input type="text" id="description" name="description" class="form-control" placeholder="Descrição" value="{{ $product->description }}" required autofocus>
                <label for="description"></label>
            </div>

            <div class="form-label-group">
                <input type="text" id="categories" name="categories" class="form-control" placeholder="Categoria" value="{{ $product->categories }}" required autofocus>
                <label for="categories"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="value" name="value" class="form-control" placeholder="Preço" value="{{ $product->value }}" required>
                <label for="value"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="quantity" name="quantity" class="form-control" placeholder="Quantidade" value="{{ $product->quantity }}" required>
                <label for="quantity"></label>
            </div>

            <div class="form-label-group">
                <input type="number" id="weight" name="weight" class="form-control" placeholder="Peso" value="{{ $product->weight }}" required>
                <label for="weight"></label>
            </div>

            <button class="btn btn-lg btn-primary btn-block text-uppercase font-weight-bold mb-2" style="background: green; border-color: green" type="submit">Editar Produto</button>
        </form>
    </div>
</div>

@endsection('content2')

resources/views/product/index.blade.php
@extends('navbar')

@section('lis')
<li class="nav-item">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')

@section('h1', 'Listagem dos seus produtos')
@section('text', 'Estes são todos os produtos que você cadastrou no sistema. Você poderá editar, excluir e visualizar eles.')
@section('content2')

<div class="row">
    <form method="GET" action="/product/filter">
        <div class="form-row">
            <div class="col-sm-2">
                <input type="number" name="id" class="form-control" placeholder="ID">
            </div>
            <div class="col-sm-3">
                <input type="text" name="title" class="form-control" placeholder="Título">
            </div>
            <div class="col-sm-3">
                <input type="text" name="categories" class="form-control" placeholder="Categoria">
            </div>
            <div class="col-sm-2">
                <input type="text" name="value" class="form-control" placeholder="Preço">
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-primary">Filtrar Produto</button>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Título</th>
                <th scope="col">Categoria</th>
                <th scope="col">Preço</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            @forelse($products as $key => $product)
            <tr>
                <th scope="row">{{json_decode($product)->id}}</th>
                <td>{{json_decode($product)->title}}</td>
                <td>{{json_decode($product)->categories}}</td>
                <td>{{json_decode($product)->value}}</td>
                <td>
                    <a href="{{ route('product.show', ['id' => json_decode($product)->id]) }}" class="btn btn-primary btn-xs center-align" style="background: #275ba0; border-color: blue;">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a href="{{ route('product.edit', ['id' => json_decode($product)->id]) }}" class="btn btn-primary btn-xs center-align" style="background: #275421; border-color: green;">
                        <i class="fas fa-edit"></i>
                    </a>
                    <button class="btn btn-primary btn-xs center-align" onclick="clickModal({{json_decode($product)->id}})" data-target="myModal" data-toggle="modal" style="background: #ac111e; border-color: red;">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </td>
            </tr>

            <!-- MODAL DE DELETE -->
            <div class="modal fade" id="myModal{{json_decode($product)->id}}">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Deletando o item: {{$product->title}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            O item selecionado está para ser removido. Você tem certeza que deseja fazer isso?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            <form method="post" action="{{ route('product.destroy', ['id' => json_decode($product)->id]) }}">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-primary">Confirmar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @empty
            @endforelse
        </tbody>
    </table>
</div>

<div class="container">
    @if (isset($dataForm))
        {!! $products->appends($dataForm)->links("pagination::bootstrap-4") !!}
    @else
        {!! $products->links("pagination::bootstrap-4") !!}
    @endif
</div>

@endsection('content2')

resources/views/product/show.blade.php
@extends('navbar')

@section('lis')
<li class="nav-item">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')

@section('h1', 'Visualizar Produto')
@section('text', 'Abaixo encontram-se os dados referentes ao produto selecionado.')
@section('content2')

<div class="row">
    <div class="col-lg-4 col-sm-6 mb-4">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{$product->title}}</a>
                </h4>
                <p class="card-text">{{$product->description}}</p>
                <hr>
                Categoria: {{$product->categories}}</br>
                Preço: {{$product->value}}<br>
                Quantidade: {{$product->quantity}}<br>
                Peso: {{$product->weight}}<br>
            </div>
        </div>
    </div>
</div>


@endsection('content2')

resources/views/template.blade.php
<html>
  <head>
      <title>@yield('title')</title>
      <meta charset="UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="{{ asset('public/css/main.css') }}" type="text/css">
      <link rel="stylesheet" href="{{ asset('public/css/app.css') }}" type="text/css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
      @yield('content')
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script scr="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
      <script type="text/javascript">
          function clickModal(ev){
              $(document).ready(function(){
                  $('#myModal'+ev).modal('toggle');
              });
          }
      </script>
  </body>
</html>

resources/views/user/authenticate.blade.php
@extends('template')

@section('title')
login
@endsection('content')

@section('content')
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-8 col-lg-8 offset-md-2">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Seja bem vindo de volta</h3>
              <form method="post" action="/user/authenticate">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-label-group">
                  <input type="email" name="email" value="{{ old('email') }}" id="inputEmail" class="form-control" placeholder="Endereço de Email" required autofocus>
                  <label for="inputEmail">Email</label>
                </div>

                <div class="form-label-group">
                  <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Senha" required>
                  <label for="inputPassword">Senha</label>
                </div>

                <div class="custom-control custom-checkbox mb-3">
                  <input type="checkbox" class="custom-control-input" id="customCheck1">
                  <label class="custom-control-label" for="customCheck1">Lembrar minha senha</label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign in</button>
                <div class="text-center">
                  <a class="small" href="#">Esqueci minha senha!</a></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection('content')

resources/views/user/create.blade.php
@extends('template')

@section('title')
Cadastrar Usuário
@endsection('content')

@section('content')
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-8 col-lg-8 offset-md-2">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Cadastre-se agora</h3>
              <form action="{{route('user.store')}}" method="post">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-label-group">
                  <input type="text" id="nome" name="name" class="form-control" placeholder="Nome completo" value="{{ old('name') }}" required autofocus>
                  <label for="nome"></label>
                </div>

                <div class="form-label-group">
                  <input type="tel" id="telefone" name="telephone" class="form-control" placeholder="Telefone" value="{{ old('telephone') }}" required autofocus>
                  <label for="telefone"></label>
                </div>

                <div class="form-label-group">
                  <input type="email" id="email" name="email" class="form-control" placeholder="Endereço de Email" value="{{ old('email') }}" required autofocus>
                  <label for="email"></label>
                </div>

                <div class="form-label-group">
                  <input type="password" id="senha" name="password" class="form-control" placeholder="Senha" value="{{ old('password') }}" required>
                  <label for="senha"></label>
                </div>

                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Cadastrar</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection('content')

resources/views/user/perfil.blade.php
@extends('navbar')

@section('lis')
<li class="nav-item">
    <a class="nav-link" href="/home">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.create')}}">Cadastrar Produto</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{route('product.index')}}">Listar seus produtos</a>
</li>
<li class="nav-item active dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> {{session('user')->name}}</a>
    <div class="dropdown-menu">
        <a href="{{ route('user.edit', ['id' => session('user')->id]) }}" class="dropdown-item">Meu Perfil</a>
        <a href="/logout" class="dropdown-item">Sair</a>
    </div>
</li>
@endsection('lis')

@section('h1', 'Meu Perfil')
@section('text', 'Dados pertencentes a sua conta. Você poderá editá-los a vontade!')
@section('content2')

<div class="row">
    <div class="col-md-9 col-lg-8">
        <form action="{{ route('user.update', ['id' => $user->id]) }}" method="POST">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="form-label-group">
                <input type="text" id="name" name="name" class="form-control" placeholder="Seu nome" value="{{ $user->name  }}" required autofocus>
                <label for="name"></label>
            </div>

            <div class="form-label-group">
                <input type="text" id="telephone" name="telephone" class="form-control" placeholder="Telefone" value="{{ $user->telephone }}" required autofocus>
                <label for="telephone"></label>
            </div>

            <div class="form-label-group">
                <input type="email" id="email" name="email" class="form-control" placeholder="E-mail" value="{{ $user->email }}" required autofocus>
                <label for="email"></label>
            </div>

            <button class="btn btn-lg btn-primary btn-block text-uppercase font-weight-bold mb-2" style="background: green; border-color: green" type="submit">Atualizar Dados</button>
        </form>
    </div>
</div>

@endsection('content2')